FORMAT: 1A

# Decider

Polls is a simple API allowing consumers to view polls and vote in them.

## Group User

Resources related to user registration and login



## Group Question

Resources related to questions in the API.

## Question [/questions/{question_id}{?access_token}]

+ Parameters
    + question_id (required, number, `1`) ... ID of the Question in form of an integer
    + access_token (required, string, `ACCESSTOKEN`) ... Access token

### View a Question's Detail [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "text": "Какое платье приодеть?",
            "creation_date": "2014-11-11T08:40:51.620Z",
            "category_id": 3,
            "author": {
                "id": 12,
                "name": "Нина Добрев",
                "avatar": "http://vignette3.wikia.nocookie.net/prettylittleliars/images/9/99/Nina_dobrev.jpg/revision/latest?cb=20131005203615"
            },
            "poll": [
                {
                    "id": 124,
                    "text": "Белое",
                    "image_url": "http://cs301806.vk.me/v301806039/3fe0/Ps1ZDUixseo.jpg",
                    "votes_count": 23
                },
                {
                    "id": 125,
                    "text": "Красное",
                    "image_url": "http://public.starlook.ru/temp/article/lookobzor/27/1/63rdAnnualPrimetimeEmmyAwardsArrivalsR-7OeiQnDDxl.jpg",
                    "votes_count": 73
                }
            ],
            "likes": 42,
            "comments": [
                {
                    "id": 12,
                    "text": "Конечно же красное, какие тут вопросы могут быть?",
                    "creation_date": "2014-11-11T08:40:51.620Z",
                    "author": {
                        "id": 16,
                        "name": "Петр Васильич",
                        "avatar": "url1"
                    },
                    "likes": 9
                },
                {
                    "id": 15,
                    "text": "Считаю, что белое. Вот так.",
                    "creation_date": "2014-11-11T08:40:51.620Z",
                    "author": {
                        "id": 19,
                        "name": "Петр Васильич 2",
                        "avatar": "url2"
                    },
                    "likes": 3
                }
            ]
        }
        
+ Response 403 (application/json)

        {
            "status": "error",
            "code": 7001,
            "msg": "Access token is invalid"
        }
        
+ Response 404 (application/json)

        {
            "status": "error",
            "code": 8001,
            "msg": "Question with specified id was not found"
        }
        


## Poll [/poll]

### Vote on a questions's poll [POST]

This action allows you to vote on a question's poll. Current example:
{
    "access_token":"ACCESSTOKEN",
    "data": {
        "question_id":1,
        "poll_item_id":12
    }
}

+ `access_token` (required, string) ... Access token
+ `question_id` (required, number) ... Question id
+ `poll_item_id` (required, number) ... Poll item id


+ Request (application/x-www-form-urlencoded)

        access_token=ACCESSTOKEN&data={"access_token":"ACCESSTOKEN","data":{"question_id":1,"poll_item_id":12}}

+ Response 201 (application/json)

        {
            "status": "ok",
            "code": 2001,
            "msg": "Success",
            "votes_count": 228
        }
     
+ Response 400 (application/json)

        {
            "status": "error",
            "code": 8000,
            "msg": "Required params are missing",
            "errors": [ ]
        }
        
+ Response 400 (application/json)

        {
            "status": "error",
            "code": 8005,
            "msg": "Some fields are invalid",
            "errors": [ ]
        }
    
+ Response 403 (application/json)

        {
            "status": "error",
            "code": 7001,
            "msg": "Access token is invalid"
        }
        
+ Response 404 (application/json)

        {
            "status": "error",
            "code": 8001,
            "msg": "Question with specified id was not found"
        }
        
+ Response 404 (application/json)

        {
            "status": "error",
            "code": 8002,
            "msg": "Poll item with specified id was not found"
        }

## Question's collection [/questions{?tab}{?limit}{?offset}{?access_token}]

+ Parameters
    + tab (optional, string, `new`) ... Question tab [new, popular, my]
    + limit (optional, number, `1`) ... Maximum number of questions to return
    + offset (optional, number, `1`) ... Questions offset
    + access_token (required, string, `ACCESSTOKEN`) ... Access token

### List All Questions [GET]

+ Response 200 (application/json)

        {
            "status": "ok",
            "code": 2000,
            "msg": "Successfully fetched questions",
            "total": 8301,
            "data": [
                {
                    "id": 1,
                    "text": "Какое платье приодеть?",
                    "creation_date": "2014-11-11T08:40:51.620Z",
                    "category_id": 3,
                    "author": {
                        "id": 12,
                        "username": "whotheforkami",
                        "last_name": "Добрев",
                        "first_name": "Нина",
                        "middle_name": "Кжижтовна",
                        "avatar": "http://vignette3.wikia.nocookie.net/prettylittleliars/images/9/99/Nina_dobrev.jpg/revision/latest?cb=20131005203615"
                    },
                    "poll": [
                        {
                            "id": 124,
                            "text": "Белое",
                            "image_url": "http://cs301806.vk.me/v301806039/3fe0/Ps1ZDUixseo.jpg",
                            "votes_count": 23
                        },
                        {
                            "id": 125,
                            "text": "Красное",
                            "image_url": "http://public.starlook.ru/temp/article/lookobzor/27/1/63rdAnnualPrimetimeEmmyAwardsArrivalsR-7OeiQnDDxl.jpg",
                            "votes_count": 73
                        }
                    ],
                    "likes_count": 42,
                    "comments_count": 2,
                    "is_anonymous": true
                },
                {
                    "id": 2,
                    "text": "Какое платье приодеть на этот раз?",
                    "creation_date": "2014-11-11T08:40:51.620Z",
                    "category_id": 3,
                    "author": {
                        "id": 12,
                        "username": "whotheforkami",
                        "last_name": "Добрев",
                        "first_name": "Нина",
                        "middle_name": "Кжижтовна",
                        "avatar": "http://vignette3.wikia.nocookie.net/prettylittleliars/images/9/99/Nina_dobrev.jpg/revision/latest?cb=20131005203615"
                    },
                    "poll": [
                        {
                            "id": 124,
                            "text": "Белое",
                            "image_url": "http://cs301806.vk.me/v301806039/3fe0/Ps1ZDUixseo.jpg",
                            "votes_count": 23
                        },
                        {
                            "id": 125,
                            "text": "Красное",
                            "image_url": "http://public.starlook.ru/temp/article/lookobzor/27/1/63rdAnnualPrimetimeEmmyAwardsArrivalsR-7OeiQnDDxl.jpg",
                            "votes_count": 73
                        }
                    ],
                    "likes_count": 54,
                    "comments_count": 10,
                    "is_anonymous": true
                }
            ]
        }
        
+ Response 400 (application/json)

        {
            "status": "error",
            "code": 8005,
            "msg": "Some parameters are invalid",
            "errors": [ ]
        }        
        
+ Response 403 (application/json)

        {
            "status": "error",
            "code": 7001,
            "msg": "Access token is invalid"
        }
        
        
+ Response 404 (application/json)

        {
            "status": "error",
            "code": 8003,
            "msg": "Tab is unknown"
        }
        
## New Question [/questions]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ `access_token` (string) - Access token
+ `text` (string) - Question's text
+ `category_id` (number) - Category id
+ `poll` (object) - Poll object
+ `is_anonymous` (boolean)

+ Request (application/json)

        {
            "access_token": "ACCESSTOKEN",
            "data": {
                "text": "Какое платье приодеть на этот раз?",
                "category_id": 3,
                "poll": [
                    {
                        "text": "Белое",
                        "image_uid": "3fdf32ef2d3f"
                    },
                    {
                        "text": "Красное",
                        "image_uid": "3fdf32ef2d3f"
                    }
                ],
                "is_anonymous": false
            }
        }

+ Response 201 (application/json)

        {
            "status": "ok",
            "code": 2001,
            "msg": "Question added",
            "data": {
                "id": 1,
                "text": "Какое платье приодеть?",
                "creation_date": "2014-11-11T08:40:51.620Z",
                "category_id": 3,
                "is_anonymous": false,
                "author": {
                    "id": 12,
                    "username": "whotheforkami",
                    "last_name": "Добрев",
                    "first_name": "Нина",
                    "middle_name": "Кжижтовна",
                    "avatar": "http://vignette3.wikia.nocookie.net/prettylittleliars/images/9/99/Nina_dobrev.jpg/revision/latest?cb=20131005203615"
                },
                "poll": [
                    {
                        "id": 124,
                        "text": "Белое",
                        "image_url": "url/././././"
                    },
                    {
                        "id": 125,
                        "text": "Красное",
                        "image_url": "url/././././"
                    }
                ],
                "likes": 42,
                "comments": [ ]
            }
        }

+ Response 400 (application/json)

        {
            "status": "error",
            "code": 8000,
            "msg": "Required params are missing",
            "errors": [ ]
        }
        
        
+ Response 400 (application/json)

        {
            "status": "error",
            "code": 8005,
            "msg": "Some fields are invalid",
            "errors": [ ]
        }
        
        
+ Response 403 (application/json)

        {
            "status": "error",
            "code": 7001,
            "msg": "Access token is invalid"
        }
        
        
+ Response 404 (application/json)

        {
            "status": "error",
            "code": 8004,
            "msg": "Category is unknown"
        }
        
